### ISSUE TITLE
docker-logentries stream.destroy() error on container start

### ISSUE THREAD

**Issue by brianwallace** [nearform/docker-logentries#11]
I am attempting to run the logentries docker container on a CoreOS host (within AWS), but I continue to receive the following error when starting the container using [fleet](https://coreos.com/docs/launching-containers/launching/launching-containers-fleet/):

```
docker[13610]: /usr/src/app/node_modules/docker-stats/node_modules/never-ending-stream/never-ending-stream.js:14
docker[13610]: stream.destroy()
docker[13610]: ^
docker[13610]: TypeError: Cannot call method 'destroy' of null
docker[13610]: at DestroyableTransform.result.destroy (/usr/src/app/node_modules/docker-stats/node_modules/never-ending-stream/never-ending-stream.js:14:12)
docker[13610]: at /usr/src/app/node_modules/docker-stats/node_modules/pump/index.js:42:43
docker[13610]: at call (/usr/src/app/node_modules/docker-stats/node_modules/pump/index.js:49:2)
docker[13610]: at Array.forEach (native)
docker[13610]: at /usr/src/app/node_modules/docker-stats/node_modules/pump/index.js:69:22
docker[13610]: at f (/usr/src/app/node_modules/docker-stats/node_modules/pump/node_modules/once/once.js:17:25)
docker[13610]: at DestroyableTransform.<anonymous> (/usr/src/app/node_modules/docker-stats/node_modules/pump/index.js:28:19)
docker[13610]: at DestroyableTransform.f (/usr/src/app/node_modules/end-of-stream/node_modules/once/once.js:17:25)
docker[13610]: at DestroyableTransform.emit (events.js:95:17)
docker[13610]: at next (/usr/src/app/node_modules/docker-stats/node_modules/never-ending-stream/never-ending-stream.js:32:28)
```

I have been able to start this container in a local dev environment when invoked by a simple `docker run`.

Is there a way to determine on which container stream this is failing?  That may help to isolate the root cause.

Any other ideas on the root cause?  I am not familiar with the `docker-stats` module (where this error appears to be coming from).

**Comment by mcollina** [comment]
Which version of Docker are you running? It seems you are not running version 1.5, and the stats module is giving you _a very bad error_ :).

**Comment by brianwallace** [comment]
@mcollina, you are correct!  I am currently running with docker v1.4.1.  I restarted the docker-logentries container with `--no-stats` and it worked beautifully.

Thank you!
