### ISSUE TITLE
get the stats, but don't get stderr/stdout

### ISSUE THREAD

**Issue by lonnblad** [nearform/docker-logentries#12]
Hi

I am running a container in docker, version: 1.5.0, with a simple golang application that both prints to stderr and stdout.
The container is running on a coreos node in vagrant which is running in virtualbox on os x.

I seem to get the stats log from the container, but I don't get the stderr/stdout logs from the application.

Any idea of what the problem might be?

BR
Fredrik

**Comment by mcollina** [comment]
There is nothing special about this container, it just uses the same API that the Docker CLI is using to fetch the logs. However, this container only sends logs that happen after it is started, not from the very beginning.

Does it produces any error/logs?

You might want to try running https://github.com/mcollina/docker-loghose#docker-usage.
This is what this library internally uses to fetch the logs.

**Comment by lonnblad** [comment]
Hey, 
solved it, for some reason we had the `-t` flag in our `docker run` cmd which made it to not work.
Got a crash with loghose so I will submit an issue there for that.

Thx!
/ Fredrik
