### ISSUE TITLE
Filter containers?

### ISSUE THREAD

**Issue by Maxim-Filimonov** [nearform/docker-logentries#13]
Is there a way to filter which container stats are getting sent to logentries? Stats is very data heavy and some containers we don't need stats for.

**Comment by mcollina** [comment]
Sorry for the late reply. How would you like them to be filtered? By image tag? By image tag with a regexp?

**Comment by jcugno** [comment]
I would actually want to filter by container name if that was possible

**Comment by Maxim-Filimonov** [comment]
I'd like to filter by name using regex

**Comment by siniar1990** [comment]
Some of the filtering capabilities have been reflected in "Logentries-Docker Community Pack". You can find this pack and upload it to your Logentries Dashboard [link](https://community.logentries.com/packs/docker/)

Examples:
1. View average memory by container ID using:
"usage!=null | groupby(id) | average(usage)"

2. View average memory by image name using:
"usage!=null | groupby(image) | average(usage)"

And more....

I'm not too sure about container name. 

@Maxim-Filimonov can you send sample log event.

**Comment by Maxim-Filimonov** [comment]
@siniar1990 the problem is not display but amount of data it sends. When we use statistics it sends gigabytes of data we don't ever look at which exceeds our current plan limit very quickly

**Comment by mcollina** [comment]
@jcugno @Maxim-Filimonov  can you please make some examples of filters, so that I understand your ideas correctly?

**Comment by Maxim-Filimonov** [comment]
@mcollina my example would be something like `/^[weave,logentries]/` if I remember regex right at this late hour. Basically filter all container data from container name weave or logentries

**Comment by mcollina** [comment]
the logentries container is already skipped automatically, but I get your point :). I hope to give a go at filtering soon.
