### ISSUE TITLE
Always sending json data whether I set --json or not

### ISSUE THREAD

**Issue by BastianHofmann** [nearform/docker-logentries#17]
The `-j / --json` flag has no effect. I checked the source and there is no check, if json is set or not.

**Comment by mcollina** [comment]
--json means to interpret the data logged by the applications as JSON. This is always sending JSON to the logentries server.

The JSON flag is to support a readable way. If you log JSON and it sent as a string inside a JSON, the output will look really ugly. The logic is here: https://github.com/mcollina/docker-loghose/blob/master/loghose.js#L16.

**Comment by BastianHofmann** [comment]
Ok got it thanks. I was confused because I saw json in my logentries dashboard.
