### ISSUE TITLE
Configuration on AWS

### ISSUE THREAD

**Issue by jlchereau** [nearform/docker-logentries#21]
When configuring the command in an AWS ECS task definition, I see no difference between

```
"command": [
  "-l <token>",
  "-k <token>",
  "-a",
  "host=`uname -n`"
],
```

and

```
"command": [
  "-l <token>",
  "-k <token>",
  "-j",
  "-a",
  "host=`uname -n`"
],
```

1) With or without -j makes no difference on the following output;
2) "host=`uname -n`" does not display the uname

![image](https://cloud.githubusercontent.com/assets/2556751/8018672/238ccaae-0c20-11e5-8c59-026204df3672.png)

Can you provide an explanation, a fix or a workaround?

**Comment by jlchereau** [comment]
In https://raw.githubusercontent.com/nearform/docker-logentries/master/index.js, opts.json does not seem to be ever tested.

**Comment by mcollina** [comment]
1. what are you logging is not valid json, so it is interpreted as a standard string. From the image I can see there are unix color codes.
2. I have no idea how to achieve the same thing of 'host=`uname -n`'  in AWS ECS, has it is a special bash thing.

The `json` option is checked in https://github.com/mcollina/docker-loghose/blob/master/loghose.js#L16.

**Comment by jlchereau** [comment]
Thank you for your response.

What I am logging is a Javascript object passed to ```console.dir``` which I expected docker-logentries to log as JSON. Maybe I should have ```console.log(JSON.stringify(obj))```.

Note that ```console.dir``` is how you would expect to log an object to the console. It is much more readable than JSON stringified esepcially with colors and I expected docker-logentries to automatically convert it.

May I suggest this as a feature request?

**Comment by mcollina** [comment]
Given there is no (fast) parser for the `console.dir` output, I don't think this will even be supported. I recommend to use [bunyan](http://npm.im/bunyan) if logging as json is your fashion.
