### ISSUE TITLE
Privileged mode requirement

### ISSUE THREAD

**Issue by Maxim-Filimonov** [nearform/docker-logentries#9]
Hi,
I've noticed that when running this container on Google Cloud it's required to use --privileged mode as it's  giving EACCES error otherwise. Not sure if is there a workaround to avoid privileged mode.
I guess it would be good to update documentation. Took me days to find out how to make it work
See the gist -> https://gist.github.com/Maxim-Filimonov/36862bc1c4535f9ab036#file-docker-log-log

**Comment by mcollina** [comment]
Can you please document your solution with --privileged?

This needs access to the docker socket, as it is documented in the README,
in order to call the Docker API to access the logs and stats.
Il giorno dom 1 mar 2015 alle 13:25 tpaktop <notifications@github.com> ha
scritto:

**Comment by Maxim-Filimonov** [comment]
I presume you are asking me to update the docs. See https://github.com/nearform/docker-logentries/pull/10

**Comment by mcollina** [comment]
Thanks, that was perfect! Cheers!
